sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:wDeoRgUOBJT4OzhJgCan3Yh5
deploy:
  api_key:
    secure: fu4lC68YzwTfA0ER9ojcqh4BmqNl5Ny8OG9k9J/5MmOcXK2WXr38+9rOCtNJNDAvwXwi5NQ8pR3QTDnb4K9HH/MR1v6WqEbrTM5NXNeNn2E5NxmZ6GjbZgx5lZRv+IjQ0n6nkTGkwHy1LMUi+7pPjljNeCAv4DiPuhh4jda+/uogS15iJGLDnZZ/6qSUI0ekHEZxlRZNSNMwyMtI6a0R6qJNJRRkHe/iQlpKdCxQON5HaOfJHj3Y1tydqtl1QfpprwSAaohBuO5YHeT3AJWFxCOIfD5TsHgXkwPDeTjpX0Ka1jUQa07p2mUImav7/wRCs11FxJol6lmNDDxryewpcY96cMgVI+HwchkZuLCB2Vw6k0T9zKEiDGeQPjZBvkzsIu+3yNEUwGwUVA/Gbc54a6aQ1V/WOkPshGkm9gyNCojqTB9M4lQE1JP96jQFOWK2mh8lvlKvyd5yM88tZhwbs4YPPWcDvqrcc+gXbLqj0e0uGN6N32+D0/BnVucsRssiITsLC7rz67+wNvXlqReakHGG1/xhPHAGngvndPP6wSB7i665HMAeYykZosT2dfOW/vx1It2h9IAGFbkO8ZhMjIOqfmADJrZimH2WRUwRHP0uedgh2iGKhpJmnQfjPusb+ezj3DGll4oHaj0iR9I4mXr7C71TKWLlkyY9SaU6O1c=
